
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/opt/homebrew/opt/openjdk@11/bin/"
      - "/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin/"
      - "/Users/lansmachine/.nvm/versions/node/v24.12.0/bin/"
      - "/Users/lansmachine/emsdk/"
      - "/Users/lansmachine/emsdk/upstream/emscripten/"
      - "/Library/Frameworks/Python.framework/Versions/3.11/bin/"
      - "/Library/Frameworks/Python.framework/Versions/3.14/bin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/Library/Apple/usr/bin/"
      - "/opt/homebrew/bin/"
      - "/Users/lansmachine/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand/"
    searched_directories:
      - "/opt/homebrew/opt/openjdk@11/bin/uname"
      - "/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin/uname"
      - "/Users/lansmachine/.nvm/versions/node/v24.12.0/bin/uname"
      - "/Users/lansmachine/emsdk/uname"
      - "/Users/lansmachine/emsdk/upstream/emscripten/uname"
      - "/Library/Frameworks/Python.framework/Versions/3.11/bin/uname"
      - "/Library/Frameworks/Python.framework/Versions/3.14/bin/uname"
      - "/usr/local/bin/uname"
      - "/System/Cryptexes/App/usr/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/opt/homebrew/opt/openjdk@11/bin"
        - "/opt/homebrew/opt/openjdk@11/bin"
        - "/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin"
        - "/opt/homebrew/opt/openjdk@11/bin"
        - "/opt/homebrew/opt/openjdk@11/bin"
        - "/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin"
        - "/Users/lansmachine/.nvm/versions/node/v24.12.0/bin"
        - "/Users/lansmachine/emsdk"
        - "/Users/lansmachine/emsdk/upstream/emscripten"
        - "/Library/Frameworks/Python.framework/Versions/3.11/bin"
        - "/Library/Frameworks/Python.framework/Versions/3.14/bin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/Library/Apple/usr/bin"
        - "/opt/homebrew/bin"
        - "/Users/lansmachine/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand"
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 23.6.0 - arm64
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/Platform/Darwin.cmake:76 (find_program)"
      - "/opt/homebrew/share/cmake/Modules/CMakeSystemSpecificInformation.cmake:32 (include)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_INSTALL_NAME_TOOL"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "install_name_tool"
    candidate_directories:
      - "/opt/homebrew/opt/openjdk@11/bin/"
      - "/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin/"
      - "/Users/lansmachine/.nvm/versions/node/v24.12.0/bin/"
      - "/Users/lansmachine/emsdk/"
      - "/Users/lansmachine/emsdk/upstream/emscripten/"
      - "/Library/Frameworks/Python.framework/Versions/3.11/bin/"
      - "/Library/Frameworks/Python.framework/Versions/3.14/bin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/Library/Apple/usr/bin/"
      - "/opt/homebrew/bin/"
      - "/Users/lansmachine/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand/"
    searched_directories:
      - "/opt/homebrew/opt/openjdk@11/bin/install_name_tool"
      - "/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin/install_name_tool"
      - "/Users/lansmachine/.nvm/versions/node/v24.12.0/bin/install_name_tool"
      - "/Users/lansmachine/emsdk/install_name_tool"
      - "/Users/lansmachine/emsdk/upstream/emscripten/install_name_tool"
      - "/Library/Frameworks/Python.framework/Versions/3.11/bin/install_name_tool"
      - "/Library/Frameworks/Python.framework/Versions/3.14/bin/install_name_tool"
      - "/usr/local/bin/install_name_tool"
      - "/System/Cryptexes/App/usr/bin/install_name_tool"
    found: "/usr/bin/install_name_tool"
    search_context:
      ENV{PATH}:
        - "/opt/homebrew/opt/openjdk@11/bin"
        - "/opt/homebrew/opt/openjdk@11/bin"
        - "/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin"
        - "/opt/homebrew/opt/openjdk@11/bin"
        - "/opt/homebrew/opt/openjdk@11/bin"
        - "/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home/bin"
        - "/Users/lansmachine/.nvm/versions/node/v24.12.0/bin"
        - "/Users/lansmachine/emsdk"
        - "/Users/lansmachine/emsdk/upstream/emscripten"
        - "/Library/Frameworks/Python.framework/Versions/3.11/bin"
        - "/Library/Frameworks/Python.framework/Versions/3.14/bin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/Library/Apple/usr/bin"
        - "/opt/homebrew/bin"
        - "/Users/lansmachine/Library/Application Support/Code/User/globalStorage/github.copilot-chat/debugCommand"
      CMAKE_INSTALL_PREFIX: "/usr/local"
...
